In [3]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [4]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [5]:
movies = pd.read_csv('Movie+Assignment+Data.csv')
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
20,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
21,Color,Marc Webb,599.0,153.0,464.0,963.0,Andrew Garfield,15000.0,262030663.0,Action|Adventure|Fantasy,...,1225.0,English,USA,PG-13,230000000.0,2012.0,10000.0,7.0,2.35,56000
22,Color,Ridley Scott,343.0,156.0,0.0,738.0,William Hurt,891.0,105219735.0,Action|Adventure|Drama|History,...,546.0,English,USA,PG-13,200000000.0,2010.0,882.0,6.7,2.35,17000
23,Color,Peter Jackson,509.0,186.0,0.0,773.0,Adam Brown,5000.0,258355354.0,Adventure|Fantasy,...,951.0,English,USA,PG-13,225000000.0,2013.0,972.0,7.9,2.35,83000
24,Color,Chris Weitz,251.0,113.0,129.0,1000.0,Eva Green,16000.0,70083519.0,Adventure|Family|Fantasy,...,666.0,English,USA,PG-13,180000000.0,2007.0,6000.0,6.1,2.35,0
25,Color,Peter Jackson,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
27,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
28,Color,Peter Berg,377.0,131.0,532.0,627.0,Alexander Skarsgård,14000.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,...,751.0,English,USA,PG-13,209000000.0,2012.0,10000.0,5.9,2.35,44000
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5013,Color,Eric Eason,28.0,79.0,3.0,42.0,Panchito Gómez,93.0,NaN,Drama|Family,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
5014,Color,Uwe Boll,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
5015,Black and White,Richard Linklater,61.0,100.0,0.0,0.0,Richard Linklater,5.0,1227508.0,Comedy|Drama,...,80.0,English,USA,R,23000.0,1991.0,0.0,7.1,1.37,2000
5016,Color,Joseph Mazzella,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
5017,Color,Travis Legge,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
5018,Color,Alex Kendrick,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
5019,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
5020,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
5021,Color,Jay Duplass,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297
5022,Black and White,Jim Chuchu,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
5023,Color,Daryl Wein,22.0,88.0,38.0,211.0,Heather Burns,331.0,76382.0,Romance,...,8.0,English,USA,NaN,15000.0,2009.0,212.0,6.2,2.35,324
5024,Color,Jason Trost,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
5025,Color,John Waters,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
5028,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
5029,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
5030,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
5031,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
5032,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
5034,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
5036,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
5037,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [8]:
# Write your code for inspection here
movies.shape
movies.info()
movies.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
color                        5024 non-null object
director_name                4939 non-null object
num_critic_for_reviews       4993 non-null float64
duration                     5028 non-null float64
director_facebook_likes      4939 non-null float64
actor_3_facebook_likes       5020 non-null float64
actor_2_name                 5030 non-null object
actor_1_facebook_likes       5036 non-null float64
gross                        4159 non-null float64
genres                       5043 non-null object
actor_1_name                 5036 non-null object
movie_title                  5043 non-null object
num_voted_users              5043 non-null int64
cast_total_facebook_likes    5043 non-null int64
actor_3_name                 5020 non-null object
facenumber_in_poster         5030 non-null float64
plot_keywords                4890 non-null object
movie_imdb_link              5043 non-null object
num_user_for_reviews         5022 non-null float64
language                     5031 non-null object
country                      5038 non-null object
content_rating               4740 non-null object
budget                       4551 non-null float64
title_year                   4935 non-null float64
actor_2_facebook_likes       5030 non-null float64
imdb_score                   5043 non-null float64
aspect_ratio                 4714 non-null float64
movie_facebook_likes         5043 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [9]:
# Write your code for column-wise null count here
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [10]:
# Write your code for row-wise null count here
movies.isnull().sum(axis=1)

0        0
1        0
2        0
3        0
4       14
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
5013     2
5014     2
5015     0
5016     5
5017     2
5018     2
5019     2
5020     5
5021     1
5022     4
5023     2
5024     1
5025     0
5026     0
5027     0
5028     3
5029     1
5030     5
5031     3
5032     4
5033     0
5034     1
5035     0
5036     3
5037     1
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [11]:
# Write your code for column-wise null percentages here
round (100 * movies.isnull().sum() / len(movies.index), 2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [80]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
movies_smaller = movies.drop(columns = ['color', 'director_facebook_likes', 'actor_1_facebook_likes', \
                                       'actor_2_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name', \
                                       'cast_total_facebook_likes', 'actor_3_name', 'duration', 'facenumber_in_poster',\
                                       'content_rating', 'country', 'movie_imdb_link', 'plot_keywords'])
print (round (100 * movies_smaller.isnull().sum() / len(movies_smaller.index), 2))
print (len(movies_smaller [ movies_smaller.gross.isna()]))
print (len(movies_smaller [ movies_smaller.budget.isna()]))
print (len(movies_smaller [ movies_smaller.aspect_ratio.isna()]))

director_name              2.06
num_critic_for_reviews     0.99
gross                     17.53
genres                     0.00
actor_1_name               0.14
movie_title                0.00
num_voted_users            0.00
num_user_for_reviews       0.42
language                   0.24
budget                     9.76
title_year                 2.14
imdb_score                 0.00
aspect_ratio               6.52
movie_facebook_likes       0.00
dtype: float64
884
492
329

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [81]:
# Write your code for dropping the rows here
movies_smaller.isnull().sum()
movies_smaller = movies_smaller [ ~movies_smaller.gross.isna()]
movies_smaller = movies_smaller [ ~movies_smaller.budget.isna()]
movies_smaller = movies_smaller [ ~movies_smaller.aspect_ratio.isna()]

print (len(movies_smaller [ movies_smaller.gross.isna()]))
print (len(movies_smaller [ movies_smaller.budget.isna()]))
print (len(movies_smaller [ movies_smaller.aspect_ratio.isna()]))

0
0
0

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [82]:
# Write your code for dropping the rows here
movies_smaller [ movies_smaller.isnull().sum(axis=1) > 5

Empty DataFrame
Columns: [director_name, num_critic_for_reviews, gross, genres, actor_1_name, movie_title, num_voted_users, num_user_for_reviews, language, budget, title_year, imdb_score, aspect_ratio, movie_facebook_likes]
Index: []

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [86]:
# Write your code for filling the NaN values in the 'language' column here
movies_smaller.loc[movies_smaller.language.isna(), 'language'] = 'English'

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [88]:
# Write your code for checking number of retained rows here
movies_smaller.info()
print (len(movies_smaller.index) / len(movies.index))

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3816 entries, 0 to 5042
Data columns (total 14 columns):
director_name             3816 non-null object
num_critic_for_reviews    3815 non-null float64
gross                     3816 non-null float64
genres                    3816 non-null object
actor_1_name              3815 non-null object
movie_title               3816 non-null object
num_voted_users           3816 non-null int64
num_user_for_reviews      3816 non-null float64
language                  3816 non-null object
budget                    3816 non-null float64
title_year                3816 non-null float64
imdb_score                3816 non-null float64
aspect_ratio              3816 non-null float64
movie_facebook_likes      3816 non-null int64
dtypes: float64(7), int64(2), object(5)
memory usage: 447.2+ KB
0.7566924449732302

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [49]:
# Write your code for unit conversion here
movies_smaller[['budget', 'gross']]

#movies_smaller.budget = movies_smaller.budget / 1000000
#movies_smaller.gross = movies_smaller.gross / 1000000
# movies_smaller = movies_smaller.reset_index()

          budget       gross
0     237.000000  760.505847
1     300.000000  309.404152
2     245.000000  200.074175
3     250.000000  448.130642
4     263.700000   73.058679
5     258.000000  336.530303
6     260.000000  200.807262
7     250.000000  458.991599
8     250.000000  301.956980
9     250.000000  330.249062
10    209.000000  200.069408
11    200.000000  168.368427
12    225.000000  423.032628
13    215.000000   89.289910
14    225.000000  291.021565
15    225.000000  141.614023
16    220.000000  623.279547
17    250.000000  241.063875
18    225.000000  179.020854
19    250.000000  255.108370
20    230.000000  262.030663
21    200.000000  105.219735
22    225.000000  258.355354
23    180.000000   70.083519
24    207.000000  218.051260
25    200.000000  658.672302
26    250.000000  407.197282
27    209.000000   65.173160
28    150.000000  652.177271
29    200.000000  304.360277
...          ...         ...
3610    0.150000    2.882062
3611    0.180000    9.437933
3612    0.160000    0.155984
3613    0.083532   30.859000
3614    0.160000    6.706368
3615    0.100000   10.174663
3616    0.100000   22.757819
3617    0.100000    5.228617
3618    0.040000    0.110536
3619    0.200000    0.059379
3620   15.000000   32.721635
3621    0.060000    3.216970
3622    0.060000    0.536767
3623    0.065000   11.529368
3624    0.060000    0.040557
3625    0.070000    0.030084
3626    0.025000   10.246600
3627    0.065000    0.389804
3628    0.042000    0.241816
3629    0.040000    0.277233
3630    0.030000    0.243768
3631    0.230000    3.151130
3632    0.027000    0.008231
3633    0.025000    2.856622
3634   35.000000   10.499968
3635    0.023000    1.227508
3636    0.015000    0.076382
3637    0.010000    0.180483
3638    0.007000    0.424760
3639    0.001100    0.085222

[3640 rows x 2 columns]

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [63]:
# Write your code for creating the profit column here
movies_smaller['profit'] = -movies_smaller.budget + movies_smaller.gross

In [74]:
# Write your code for sorting the dataframe here
# movies_smaller = movies_smaller.sort_values('profit', ascending = False)
movies_smaller=movies_smaller.drop(columns=['index'])

In [76]:
top10 = movies_smaller.head(10)
#movies_smaller [movies_smaller['director_name'] == 'James Cameron']
print (top10)

          director_name  num_critic_for_reviews       gross  \
0         James Cameron                   723.0  760.505847
28      Colin Trevorrow                   644.0  652.177271
25        James Cameron                   315.0  658.672302
2651       George Lucas                   282.0  460.935665
2694   Steven Spielberg                   215.0  434.949459
16          Joss Whedon                   703.0  623.279547
483        Roger Allers                   186.0  422.783777
232        George Lucas                   320.0  474.544677
64    Christopher Nolan                   645.0  533.316061
422           Gary Ross                   673.0  407.999255

                                        genres         actor_1_name  \
0              Action|Adventure|Fantasy|Sci-Fi          CCH Pounder
28            Action|Adventure|Sci-Fi|Thriller  Bryce Dallas Howard
25                               Drama|Romance    Leonardo DiCaprio
2651           Action|Adventure|Fantasy|Sci-Fi        Harrison Ford
2694                             Family|Sci-Fi         Henry Thomas
16                     Action|Adventure|Sci-Fi      Chris Hemsworth
483   Adventure|Animation|Drama|Family|Musical    Matthew Broderick
232            Action|Adventure|Fantasy|Sci-Fi      Natalie Portman
64                 Action|Crime|Drama|Thriller       Christian Bale
422            Adventure|Drama|Sci-Fi|Thriller    Jennifer Lawrence

                                     movie_title  num_voted_users  \
0                                        Avatar            886204
28                               Jurassic World            418214
25                                      Titanic            793059
2651         Star Wars: Episode IV - A New Hope            911097
2694                 E.T. the Extra-Terrestrial            281842
16                                 The Avengers            995415
483                               The Lion King            644348
232   Star Wars: Episode I - The Phantom Menace            534658
64                              The Dark Knight           1676169
422                            The Hunger Games            701607

      num_user_for_reviews language  budget  title_year  imdb_score  \
0                   3054.0  English   237.0      2009.0         7.9
28                  1290.0  English   150.0      2015.0         7.0
25                  2528.0  English   200.0      1997.0         7.7
2651                1470.0  English    11.0      1977.0         8.7
2694                 515.0  English    10.5      1982.0         7.9
16                  1722.0  English   220.0      2012.0         8.1
483                  656.0  English    45.0      1994.0         8.5
232                 3597.0  English   115.0      1999.0         6.5
64                  4667.0  English   185.0      2008.0         9.0
422                 1959.0  English    78.0      2012.0         7.3

      aspect_ratio  movie_facebook_likes      profit
0             1.78                 33000  523.505847
28            2.00                150000  502.177271
25            2.35                 26000  458.672302
2651          2.35                 33000  449.935665
2694          1.85                 34000  424.449459
16            1.85                123000  403.279547
483           1.66                 17000  377.783777
232           2.35                 13000  359.544677
64            2.35                 37000  348.316061
422           2.35                140000  329.999255

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [75]:
# Write your code for dropping duplicate values here
movies_smaller = movies_smaller.drop_duplicates()
movies_smaller[movies_smaller.index.isin([16, 752])]

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes,profit
16,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,1.85,123000,403.279547

In [ ]:
# Write code for repeating subtask 2 here

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [110]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
IMDb_Top_250 = movies_smaller[movies_smaller.num_voted_users>25000].sort_values('imdb_score', ascending=False).head(250)
IMDb_Top_250['Rank'] = range(1, 251)
IMDb_Top_250.head(10)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes,Rank
1937,Frank Darabont,199.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25000000.0,1994.0,9.3,1.85,108000,1
3466,Francis Ford Coppola,208.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6000000.0,1972.0,9.2,1.85,43000,2
2837,Francis Ford Coppola,149.0,57300000.0,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13000000.0,1974.0,9.0,1.85,14000,3
66,Christopher Nolan,645.0,533316061.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185000000.0,2008.0,9.0,2.35,37000,4
4498,Sergio Leone,181.0,6100000.0,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1200000.0,1966.0,8.9,2.35,20000,5
339,Peter Jackson,328.0,377019252.0,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94000000.0,2003.0,8.9,2.35,16000,6
1874,Steven Spielberg,174.0,96067179.0,Biography|Drama|History,Liam Neeson,Schindler's List,865020,1273.0,English,22000000.0,1993.0,8.9,1.85,41000,7
3355,Quentin Tarantino,215.0,107930000.0,Crime|Drama,Bruce Willis,Pulp Fiction,1324680,2195.0,English,8000000.0,1994.0,8.9,2.35,45000,8
270,Peter Jackson,297.0,313837577.0,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Fellowship of the R...,1238746,5060.0,English,93000000.0,2001.0,8.8,2.35,21000,9
683,David Fincher,315.0,37023395.0,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63000000.0,1999.0,8.8,2.35,48000,10

In [101]:
Top_Foreign_Lang_Film = IMDb_Top_250[ IMDb_Top_250.language != 'English']
Top_Foreign_Lang_Film.head(50)
#Top_Foreign_Lang_Film[Top_Foreign_Lang_Film.movie_title=='Veer-Zaara ']
#movies[movies.index==3510]

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes
4498,Sergio Leone,181.0,6100000.0,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.200000e+06,1966.0,8.9,2.35,20000
4029,Fernando Meirelles,214.0,7563397.0,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.300000e+06,2002.0,8.7,1.85,28000
4747,Akira Kurosawa,153.0,269061.0,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.000000e+06,1954.0,8.7,1.37,11000
2373,Hayao Miyazaki,246.0,10049886.0,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,1.900000e+07,2001.0,8.6,1.85,28000
3931,Ron Fricke,115.0,2601847.0,Documentary|Music,Collin Alfredo St. Dic,Samsara,22457,69.0,None,4.000000e+06,2011.0,8.5,2.35,26000
4259,Florian Henckel von Donnersmarck,215.0,11284657.0,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.000000e+06,2006.0,8.5,2.35,39000
4921,Majid Majidi,46.0,925402.0,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,1.800000e+05,1997.0,8.5,1.85,0
2970,Wolfgang Petersen,96.0,11433134.0,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426.0,German,1.400000e+07,1981.0,8.4,1.85,11000
1298,Jean-Pierre Jeunet,242.0,33201661.0,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314.0,French,7.700000e+07,2001.0,8.4,2.35,39000
1329,S.S. Rajamouli,44.0,6498000.0,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,1.802615e+07,2015.0,8.4,1.85,21000
4659,Asghar Farhadi,354.0,7098492.0,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,5.000000e+05,2011.0,8.4,1.85,48000
2323,Hayao Miyazaki,174.0,2298191.0,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2.400000e+09,1997.0,8.4,1.85,11000
4105,Chan-wook Park,305.0,2181290.0,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.000000e+06,2003.0,8.4,2.35,43000
2829,Oliver Hirschbiegel,192.0,5501940.0,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,1.350000e+07,2004.0,8.3,1.85,14000
2734,Fritz Lang,260.0,26435.0,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.000000e+06,1927.0,8.3,1.33,12000
4033,Thomas Vinterberg,349.0,610968.0,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.800000e+06,2012.0,8.3,2.35,60000
4000,Juan José Campanella,262.0,20167424.0,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231.0,Spanish,2.000000e+06,2009.0,8.2,2.35,33000
2551,Guillermo del Toro,406.0,37623143.0,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,1.350000e+07,2006.0,8.2,1.85,27000
2047,Hayao Miyazaki,212.0,4710455.0,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,2.400000e+07,2004.0,8.2,1.85,13000
4585,Joshua Oppenheimer,248.0,484221.0,Biography|Crime|Documentary|History,Anwar Congo,The Act of Killing,23836,107.0,Indonesian,1.000000e+06,2012.0,8.2,1.85,20000
3550,Denis Villeneuve,226.0,6857096.0,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.800000e+06,2010.0,8.2,1.85,37000
2830,Alejandro Amenábar,157.0,2086345.0,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,1.000000e+07,2004.0,8.1,2.35,0
3423,Katsuhiro Ôtomo,150.0,439162.0,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1.100000e+09,1988.0,8.1,1.85,0
4267,Alejandro G. Iñárritu,157.0,5383834.0,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.000000e+06,2000.0,8.1,1.85,11000
2914,Je-kyu Kang,86.0,1110186.0,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,1.280000e+07,2004.0,8.1,2.35,0
3553,José Padilha,142.0,8060.0,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.000000e+06,2007.0,8.1,1.85,11000
4461,Thomas Vinterberg,98.0,1647780.0,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.300000e+06,1998.0,8.1,1.33,5000
3456,Vincent Paronnaud,242.0,4443403.0,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158.0,French,7.300000e+06,2007.0,8.0,1.85,14000
4284,Ari Folman,231.0,2283276.0,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156.0,Hebrew,1.500000e+06,2008.0,8.0,1.85,0
4897,Sergio Leone,122.0,3500000.0,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235.0,Italian,2.000000e+05,1964.0,8.0,2.35,0
3344,Karan Johar,210.0,4018695.0,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,1.200000e+07,2010.0,8.0,2.35,27000
4144,Walter Salles,71.0,5595428.0,Drama,Fernanda Montenegro,Central Station,28951,257.0,Portuguese,2.900000e+06,1998.0,8.0,2.35,0
3510,Yash Chopra,29.0,2921738.0,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.000000e+06,2004.0,7.9,2.35,2000
4499,Anna Muylaert,111.0,375723.0,Comedy|Drama,Alex Huszar,The Second Mother,7025,26.0,Portuguese,4.000000e+06,2015.0,7.9,2.35,0
1171,Yimou Zhang,283.0,84961.0,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,3.100000e+07,2002.0,7.9,2.35,0
2919,Stéphane Aubier,99.0,71442.0,Animation|Comedy|Crime|Drama|Family,Mackenzie Foy,Ernest & Celestine,12029,32.0,French,9.600000e+06,2012.0,7.9,1.85,0
2605,Ang Lee,287.0,128067808.0,Action|Drama|Romance,Chen Chang,"Crouching Tiger, Hidden Dragon",217740,1641.0,Mandarin,1.500000e+07,2000.0,7.9,2.35,0
3677,Christophe Barratier,112.0,3629758.0,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.500000e+06,2004.0,7.9,2.35,0
2863,Clint Eastwood,251.0,13753931.0,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,1.900000e+07,2006.0,7.9,2.35,5000
4415,Fabián Bielinsky,94.0,1221261.0,Crime|Drama|Thriller,Ricardo Darín,Nine Queens,38215,125.0,Spanish,1.500000e+06,2000.0,7.9,1.85,0
2493,Yimou Zhang,283.0,84961.0,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,3.100000e+07,2002.0,7.9,2.35,0
3264,Michael Haneke,447.0,225377.0,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.900000e+06,2012.0,7.9,1.85,33000
4640,Cristian Mungiu,233.0,1185783.0,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,5.900000e+05,2007.0,7.9,1.85,14000
3856,Mike van Diem,54.0,713413.0,Crime|Drama|Mystery,Jan Decleir,Character,9171,68.0,Dutch,4.500000e+06,1997.0,7.8,1.85,689
4385,Ritesh Batra,195.0,4231500.0,Drama|Romance,Nawazuddin Siddiqui,The Lunchbox,30479,162.0,Hindi,1.000000e+06,2013.0,7.8,2.35,16000
1236,Mel Gibson,283.0,50859889.0,Action|Adventure|Drama|Thriller,Rudy Youngblood,Apocalypto,236000,1043.0,Maya,4.000000e+07,2006.0,7.8,1.85,14000
2256,Stephen Chow,377.0,17104669.0,Action|Comedy|Crime|Fantasy,Shengyi Huang,Kung Fu Hustle,99353,354.0,Cantonese,2.000000e+07,2004.0,7.8,2.35,0
4263,Sylvain Chomet,167.0,7002255.0,Animation|Comedy|Drama,Michel Robin,The Triplets of Belleville,42462,312.0,French,9.500000e+06,2003.0,7.8,1.66,0
2460,Michael Haneke,292.0,2222647.0,Drama|Mystery,Ulrich Tukur,The White Ribbon,52958,193.0,German,1.200000e+07,2009.0,7.8,1.85,0
504,Jacques Perrin,113.0,19406406.0,Documentary|Drama,Pedro Armendáriz Jr.,Oceans,7630,42.0,French,4.000000e+07,2009.0,7.8,2.35,0

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [178]:
# Write your code for extracting the top 10 directors here
# it250=IMDb_Top_250[:]

top_dirs = movies_smaller.groupby('director_name')['imdb_score'].mean()
top_dirs = top_dirs.reset_index()
top_dirs.columns = ['director_name', 'mean_imdb']
top_dirs = top_dirs.sort_values('mean_imdb', ascending=False)
top_dirs

              director_name  mean_imdb
1624              Tony Kaye   8.600000
211         Charles Chaplin   8.600000
294         Damien Chazelle   8.500000
1398             Ron Fricke   8.500000
984            Majid Majidi   8.500000
44         Alfred Hitchcock   8.500000
1453           Sergio Leone   8.433333
255       Christopher Nolan   8.425000
100          Asghar Farhadi   8.400000
1423         S.S. Rajamouli   8.400000
1332       Richard Marquand   8.400000
212        Charles Ferguson   8.300000
140            Billy Wilder   8.300000
950        Lenny Abrahamson   8.300000
493              Fritz Lang   8.300000
946             Lee Unkrich   8.300000
1240            Pete Docter   8.233333
585          Hayao Miyazaki   8.225000
1291      Quentin Tarantino   8.200000
853      Joshua Oppenheimer   8.200000
434              Elia Kazan   8.200000
532         George Roy Hill   8.200000
859    Juan José Campanella   8.200000
1644         Victor Fleming   8.150000
1132           Milos Forman   8.133333
676             Je-kyu Kang   8.100000
1580             Tim Miller   8.100000
14           Akira Kurosawa   8.100000
1559           Terry George   8.100000
1680          William Wyler   8.100000
...                     ...        ...
570             Hal Needham   3.500000
1632            Troy Miller   3.400000
579            Harold Cronk   3.400000
506             Gary Rogers   3.300000
19              Alan Metter   3.300000
1596              Tom Brady   3.300000
925            Klaus Menzel   3.300000
1286                  Pitof   3.300000
404        Don Michael Paul   3.300000
97             Arjun Sablok   3.300000
150              Bob Spiers   3.300000
1239    Perry Andelin Blake   3.300000
253      Christopher Leitch   3.200000
1641          Vic Armstrong   3.100000
1629           Trent Cooper   3.100000
215   Charles Robert Carner   3.100000
717             Jim Goddard   3.000000
1639               Uwe Boll   3.000000
1178          Nnegest Likké   3.000000
488             Fred Savage   2.900000
845          Joseph Sargent   2.800000
326          Dave Borthwick   2.800000
893         Kenneth Johnson   2.800000
1508            Steve Gomer   2.800000
1             Aaron Seltzer   2.700000
1340       Rick de Oliveira   2.700000
665         Jason Friedberg   2.600000
1389        Roger Christian   2.400000
39                Alex Zamm   2.300000
1652     Vondie Curtis-Hall   2.100000

[1699 rows x 2 columns]


**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [185]:
# Write your code for extracting the first two genres of each movie here
movies_smaller['g'] = movies_smaller.genres.str.split('|')
movies_smaller['genre_1'] = movies_smaller.g.apply(lambda x : x[0])
movies_smaller['genre_2'] = movies_smaller.g.apply(lambda x : x[1] if len(x) > 1 else x[0])

In [186]:
movies_by_segment = movies_smaller.groupby(['genre_1', 'genre_2'])

In [187]:
#PopGenre = movies_by_segment['gross'].mean()['genre_1', 'genre_2']
movies_by_segment['gross'].mean().reset_index().sort_values('gross', ascending=False).head()

      genre_1    genre_2         gross
83     Family     Sci-Fi  4.349495e+08
28  Adventure     Sci-Fi  2.286278e+08
24  Adventure     Family  1.199166e+08
18  Adventure  Animation  1.179342e+08
1      Action  Adventure  1.109113e+08

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_reviews` and identify the actors which have the highest mean.

In [159]:
# Write your code for creating three new dataframes here

Meryl_Streep = movies_smaller[movies_smaller.actor_1_name == 'Meryl Streep']

In [160]:
Leo_Caprio = movies_smaller[movies_smaller.actor_1_name=='Leonardo DiCaprio']

In [161]:
Brad_Pitt = movies_smaller[movies_smaller.actor_1_name=='Brad Pitt']

In [174]:
# Write your code for combining the three dataframes here
Combined = pd.concat([Meryl_Streep, Leo_Caprio, Brad_Pitt])
Combined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49 entries, 410 to 2898
Data columns (total 16 columns):
director_name             49 non-null object
num_critic_for_reviews    49 non-null float64
gross                     49 non-null float64
genres                    49 non-null object
actor_1_name              49 non-null object
movie_title               49 non-null object
num_voted_users           49 non-null int64
num_user_for_reviews      49 non-null float64
language                  49 non-null object
budget                    49 non-null float64
title_year                49 non-null float64
imdb_score                49 non-null float64
aspect_ratio              49 non-null float64
movie_facebook_likes      49 non-null int64
genre_1                   49 non-null object
genre_2                   49 non-null object
dtypes: float64(7), int64(2), object(7)
memory usage: 6.5+ KB

In [170]:
# Write your code for grouping the combined dataframe here
actor_group = Combined.groupby('actor_1_name')

In [177]:
# Write the code for finding the mean of critic reviews and audience reviews here
print (actor_group[['num_critic_for_reviews', 'num_user_for_reviews']].mean().reset_index())

        actor_1_name  num_critic_for_reviews  num_user_for_reviews
0          Brad Pitt              245.000000            742.352941
1  Leonardo DiCaprio              330.190476            914.476190
2       Meryl Streep              181.454545            297.181818

**Checkpoint 6:** `Leonardo` has aced both the lists!